// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreInvoice.Acceptance.Tests.Features.ShoppingCarts.UpdateShoppingCartSuccess
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UpdateShoppingCartFeature : object, global::Xunit.IClassFixture<UpdateShoppingCartFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/ShoppingCarts/UpdateShoppingCartSuccess", "Update shopping cart", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateShoppingCartSuccess.feature"
#line hidden
        
        public UpdateShoppingCartFeature(UpdateShoppingCartFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ShoppingCarts/UpdateShoppingCartSuccess/UpdateShoppingCartSuccess.featur" +
                    "e.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update shopping cart returns updated shopping cart")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update shopping cart")]
        [global::Xunit.TraitAttribute("Description", "Update shopping cart returns updated shopping cart")]
        public async global::System.Threading.Tasks.Task UpdateShoppingCartReturnsUpdatedShoppingCart()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update shopping cart returns updated shopping cart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
    await testRunner.GivenAsync("I have an existing shopping cart for update", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table20.AddRow(new string[] {
                            "Line1ProductId",
                            "11111111-1111-1111-1111-111111111111"});
                table20.AddRow(new string[] {
                            "Line1Name",
                            "Phone"});
                table20.AddRow(new string[] {
                            "Line1Brand",
                            "Apple"});
                table20.AddRow(new string[] {
                            "Line1UnitPriceAmount",
                            "999.99"});
                table20.AddRow(new string[] {
                            "Line1UnitPriceCurrency",
                            "usd"});
                table20.AddRow(new string[] {
                            "Line1Quantity",
                            "2"});
                table20.AddRow(new string[] {
                            "Line2ProductId",
                            "22222222-2222-2222-2222-222222222222"});
                table20.AddRow(new string[] {
                            "Line2Name",
                            "Watch"});
                table20.AddRow(new string[] {
                            "Line2Brand",
                            "Apple"});
                table20.AddRow(new string[] {
                            "Line2UnitPriceAmount",
                            "399.99"});
                table20.AddRow(new string[] {
                            "Line2UnitPriceCurrency",
                            "usd"});
                table20.AddRow(new string[] {
                            "Line2Quantity",
                            "1"});
#line 5
    await testRunner.AndAsync("I have a valid update shopping cart request", ((string)(null)), table20, "And ");
#line hidden
#line 19
    await testRunner.WhenAsync("I submit the update shopping cart request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table21.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table21.AddRow(new string[] {
                            "HasId",
                            "true"});
                table21.AddRow(new string[] {
                            "HasClientId",
                            "true"});
                table21.AddRow(new string[] {
                            "ClientId",
                            "from-scenario-client-id"});
                table21.AddRow(new string[] {
                            "TotalAmount",
                            "2399.97"});
                table21.AddRow(new string[] {
                            "TotalCurrency",
                            "USD"});
                table21.AddRow(new string[] {
                            "LinesCount",
                            "2"});
                table21.AddRow(new string[] {
                            "Line1Name",
                            "Phone"});
                table21.AddRow(new string[] {
                            "Line1Brand",
                            "Apple"});
                table21.AddRow(new string[] {
                            "Line1Quantity",
                            "2"});
                table21.AddRow(new string[] {
                            "Line1TotalAmount",
                            "1999.98"});
                table21.AddRow(new string[] {
                            "Line1TotalCurrency",
                            "USD"});
                table21.AddRow(new string[] {
                            "Line2Name",
                            "Watch"});
                table21.AddRow(new string[] {
                            "Line2Brand",
                            "Apple"});
                table21.AddRow(new string[] {
                            "Line2Quantity",
                            "1"});
                table21.AddRow(new string[] {
                            "Line2TotalAmount",
                            "399.99"});
                table21.AddRow(new string[] {
                            "Line2TotalCurrency",
                            "USD"});
#line 20
    await testRunner.ThenAsync("the shopping cart is updated successfully", ((string)(null)), table21, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateShoppingCartFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateShoppingCartFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
