services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "admin", "--password", "admin123", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  ecommercestoreinvoice.api:
    image: ${DOCKER_REGISTRY-}ecommercestoreinvoiceapi
    build:
      context: .
      dockerfile: src/ECommerceStoreInvoice.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_HTTP_PORTS: 8080
      MongoDbSettings__ConnectionString: mongodb://admin:admin123@mongodb:27017/?authSource=admin
      MongoDbSettings__DatabaseName: ecommerce-store-invoice-db
      MongoDbSettings__ShoppingCartsCollectionName: shopping-carts
      MongoDbSettings__OrdersCollectionName: orders
      MongoDbSettings__ProductVersionsCollectionName: product-versions
      MongoDbSettings__InvoicesCollectionName: invoices
    ports:
      - "8080:8080"
    shm_size: "2gb"

volumes:
  mongo_data: