// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreInvoice.Acceptance.Tests.Features.Invoices.CreateInvoiceForOrderConflict
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_creating_invoice_for_order_when_invoice_already_exists" +
        "_returns_conflict_problem_details.")]
    public partial class CreateInvoiceForOrderConflictFeature : object, global::Xunit.IClassFixture<CreateInvoiceForOrderConflictFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_creating_invoice_for_order_when_invoice_already_exists" +
                    "_returns_conflict_problem_details."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Invoices/CreateInvoiceForOrderConflict", "Create invoice for order conflict", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateInvoiceForOrderConflict.feature"
#line hidden
        
        public CreateInvoiceForOrderConflictFeature(CreateInvoiceForOrderConflictFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Invoices/CreateInvoiceForOrderConflict/CreateInvoiceForOrderConflict.fea" +
                    "ture.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create invoice for order returns conflict when invoice already exists")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create invoice for order conflict")]
        [global::Xunit.TraitAttribute("Description", "Create invoice for order returns conflict when invoice already exists")]
        public async global::System.Threading.Tasks.Task CreateInvoiceForOrderReturnsConflictWhenInvoiceAlreadyExists()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create invoice for order returns conflict when invoice already exists", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "ClientName",
                            "John Doe"});
                table1.AddRow(new string[] {
                            "PostalCode",
                            "00-001"});
                table1.AddRow(new string[] {
                            "City",
                            "NewYork"});
                table1.AddRow(new string[] {
                            "Street",
                            "Main.St"});
                table1.AddRow(new string[] {
                            "BuildingNumber",
                            "10A"});
                table1.AddRow(new string[] {
                            "ApartmentNumber",
                            "5"});
                table1.AddRow(new string[] {
                            "PhoneNumber",
                            "123456789"});
                table1.AddRow(new string[] {
                            "PhonePrefix",
                            "48"});
                table1.AddRow(new string[] {
                            "AddressEmail",
                            "john.doe@test.com"});
                table1.AddRow(new string[] {
                            "ProductName",
                            "Laptop"});
                table1.AddRow(new string[] {
                            "ProductBrand",
                            "Lenovo"});
                table1.AddRow(new string[] {
                            "UnitPriceAmount",
                            "999.99"});
                table1.AddRow(new string[] {
                            "UnitPriceCurrency",
                            "usd"});
                table1.AddRow(new string[] {
                            "Quantity",
                            "2"});
                table1.AddRow(new string[] {
                            "OrderStatus",
                            "Paid"});
#line 5
    await testRunner.GivenAsync("I have an existing invoice for a paid order", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "HasBody",
                            "false"});
#line 22
    await testRunner.WhenAsync("I submit the duplicate create invoice for order request", ((string)(null)), table2, "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "StatusCode",
                            "409"});
                table3.AddRow(new string[] {
                            "Title",
                            "Conflict."});
                table3.AddRow(new string[] {
                            "HasDetailWithOrderId",
                            "true"});
                table3.AddRow(new string[] {
                            "Type",
                            "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.8"});
#line 25
    await testRunner.ThenAsync("duplicate create invoice for order returns conflict", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreateInvoiceForOrderConflictFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreateInvoiceForOrderConflictFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
