// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreInvoice.Acceptance.Tests.Features.ClientDataVersions.CreateClientDataVersionSuccess
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_creating_client_data_version_returns_a_success_respons" +
        "e_with_the_created_payload_fields.")]
    public partial class CreateClientDataVersionFeature : object, global::Xunit.IClassFixture<CreateClientDataVersionFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_creating_client_data_version_returns_a_success_respons" +
                    "e_with_the_created_payload_fields."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/ClientDataVersions/CreateClientDataVersionSuccess", "Create client data version", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateClientDataVersionSuccess.feature"
#line hidden
        
        public CreateClientDataVersionFeature(CreateClientDataVersionFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ClientDataVersions/CreateClientDataVersionSuccess/CreateClientDataVersio" +
                    "nSuccess.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create client data version returns created client data version")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create client data version")]
        [global::Xunit.TraitAttribute("Description", "Create client data version returns created client data version")]
        public async global::System.Threading.Tasks.Task CreateClientDataVersionReturnsCreatedClientDataVersion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create client data version returns created client data version", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("I have a valid client id for client data version creation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "ClientName",
                            "John Doe"});
                table1.AddRow(new string[] {
                            "PostalCode",
                            "00-001"});
                table1.AddRow(new string[] {
                            "City",
                            "NewYork"});
                table1.AddRow(new string[] {
                            "Street",
                            "Main.St"});
                table1.AddRow(new string[] {
                            "BuildingNumber",
                            "10A"});
                table1.AddRow(new string[] {
                            "ApartmentNumber",
                            "5"});
                table1.AddRow(new string[] {
                            "PhoneNumber",
                            "123456789"});
                table1.AddRow(new string[] {
                            "PhonePrefix",
                            "48"});
                table1.AddRow(new string[] {
                            "AddressEmail",
                            "john.doe@test.com"});
#line 6
    await testRunner.AndAsync("I have a valid create client data version request", ((string)(null)), table1, "And ");
#line hidden
#line 17
    await testRunner.WhenAsync("I submit the create client data version request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table2.AddRow(new string[] {
                            "HasId",
                            "true"});
                table2.AddRow(new string[] {
                            "HasClientId",
                            "true"});
                table2.AddRow(new string[] {
                            "ClientName",
                            "John Doe"});
                table2.AddRow(new string[] {
                            "PostalCode",
                            "00-001"});
                table2.AddRow(new string[] {
                            "City",
                            "NewYork"});
                table2.AddRow(new string[] {
                            "Street",
                            "Main.St"});
                table2.AddRow(new string[] {
                            "BuildingNumber",
                            "10A"});
                table2.AddRow(new string[] {
                            "ApartmentNumber",
                            "5"});
                table2.AddRow(new string[] {
                            "PhoneNumber",
                            "123456789"});
                table2.AddRow(new string[] {
                            "PhonePrefix",
                            "48"});
                table2.AddRow(new string[] {
                            "AddressEmail",
                            "john.doe@test.com"});
                table2.AddRow(new string[] {
                            "HasCreatedAt",
                            "true"});
#line 18
    await testRunner.ThenAsync("the client data version is created successfully", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreateClientDataVersionFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreateClientDataVersionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
