// <auto-generated/>
#pragma warning disable CS0618
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Currencies;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductApiClient : BaseRequestBuilder
    {
        /// <summary>The categories property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The currencies property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Currencies.CurrenciesRequestBuilder Currencies
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Currencies.CurrenciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mobilePhones property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder MobilePhones
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productsDocumentation property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ProductsDocumentationRequestBuilder ProductsDocumentation
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ProductsDocumentationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
