// <auto-generated/>
#pragma warning disable CS0618
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \categories\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CategoriesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.Item.CategoriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoriesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/categories/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.Item.CategoriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoriesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/categories/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Soft deletes a category and returns the deactivated resource.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ApiProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ApiProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto>(requestInfo, global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the category when the ID exists; 404 otherwise.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.NotFoundProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.NotFoundProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto>(requestInfo, global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates an existing category and returns the updated resource.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ApiProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto?> PutAsync(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateCategoryExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto> PutAsync(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateCategoryExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ApiProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto>(requestInfo, global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Soft deletes a category and returns the deactivated resource.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns the category when the ID exists; 404 otherwise.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates an existing category and returns the updated resource.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateCategoryExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateCategoryExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.Item.CategoriesItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.Item.CategoriesItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Categories.Item.CategoriesItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CategoriesItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CategoriesItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CategoriesItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
