// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateSatelliteNavigationSystemExternalDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The agps property</summary>
        public bool? Agps { get; set; }
        /// <summary>The galileo property</summary>
        public bool? Galileo { get; set; }
        /// <summary>The glonass property</summary>
        public bool? Glonass { get; set; }
        /// <summary>The gps property</summary>
        public bool? Gps { get; set; }
        /// <summary>The qzss property</summary>
        public bool? Qzss { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateSatelliteNavigationSystemExternalDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateSatelliteNavigationSystemExternalDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateSatelliteNavigationSystemExternalDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agps", n => { Agps = n.GetBoolValue(); } },
                { "galileo", n => { Galileo = n.GetBoolValue(); } },
                { "glonass", n => { Glonass = n.GetBoolValue(); } },
                { "gps", n => { Gps = n.GetBoolValue(); } },
                { "qzss", n => { Qzss = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("agps", Agps);
            writer.WriteBoolValue("galileo", Galileo);
            writer.WriteBoolValue("glonass", Glonass);
            writer.WriteBoolValue("gps", Gps);
            writer.WriteBoolValue("qzss", Qzss);
        }
    }
}
#pragma warning restore CS0618
