// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MobilePhoneFilterDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The brand property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhonesBrand? Brand { get; set; }
        /// <summary>The maximalPrice property</summary>
        public double? MaximalPrice { get; set; }
        /// <summary>The minimalPrice property</summary>
        public double? MinimalPrice { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneFilterDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneFilterDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneFilterDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brand", n => { Brand = n.GetEnumValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhonesBrand>(); } },
                { "maximalPrice", n => { MaximalPrice = n.GetDoubleValue(); } },
                { "minimalPrice", n => { MinimalPrice = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhonesBrand>("brand", Brand);
            writer.WriteDoubleValue("maximalPrice", MaximalPrice);
            writer.WriteDoubleValue("minimalPrice", MinimalPrice);
        }
    }
}
#pragma warning restore CS0618
