// <auto-generated/>
#pragma warning disable CS0618
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow
{
    /// <summary>
    /// Builds and executes requests for operations under \products-documentation\flow
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FlowRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FlowRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products-documentation/flow", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FlowRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products-documentation/flow", rawUrl)
        {
        }
        /// <summary>
        /// Returns the ordered steps executed when handling every documented request.
        /// </summary>
        /// <returns>A List&lt;global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.FlowDescription&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.FlowDescription>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.FlowDescription>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.FlowDescription>(requestInfo, global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.FlowDescription.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns the ordered steps executed when handling every documented request.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FlowRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
