// <auto-generated/>
#pragma warning disable CS0618
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Filter;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Top;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones
{
    /// <summary>
    /// Builds and executes requests for operations under \mobile-phones
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MobilePhonesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filter property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Filter.FilterRequestBuilder Filter
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Filter.FilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Top.TopRequestBuilder Top
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Top.TopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ECommerceStoreInvoice.Infrastructure.ApiClients.Products.mobilePhones.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item.MobilePhonesItemRequestBuilder"/></returns>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item.MobilePhonesItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item.MobilePhonesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ECommerceStoreInvoice.Infrastructure.ApiClients.Products.mobilePhones.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item.MobilePhonesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item.MobilePhonesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.Item.MobilePhonesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MobilePhonesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mobile-phones", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MobilePhonesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mobile-phones", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of mobile phones limited by the provided amount.
        /// </summary>
        /// <returns>A List&lt;global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDto>?> GetAsync(Action<RequestConfiguration<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder.MobilePhonesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDto>> GetAsync(Action<RequestConfiguration<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder.MobilePhonesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDto>(requestInfo, global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Creates a new mobile phone and returns the created resource.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDetailsDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ApiProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDetailsDto?> PostAsync(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateMobilePhoneExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDetailsDto> PostAsync(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateMobilePhoneExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ApiProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDetailsDto>(requestInfo, global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneDetailsDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of mobile phones limited by the provided amount.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder.MobilePhonesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder.MobilePhonesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/mobile-phones?amount={amount}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new mobile phone and returns the created resource.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateMobilePhoneExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CreateMobilePhoneExternalDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of mobile phones limited by the provided amount.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MobilePhonesRequestBuilderGetQueryParameters 
        {
            [QueryParameter("amount")]
            public int? Amount { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MobilePhonesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.MobilePhones.MobilePhonesRequestBuilder.MobilePhonesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MobilePhonesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
