// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ElectronicDetailsDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The batteryCapacity property</summary>
        public int? BatteryCapacity { get; set; }
        /// <summary>The batteryType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryType { get; set; }
#nullable restore
#else
        public string BatteryType { get; set; }
#endif
        /// <summary>The cpu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cpu { get; set; }
#nullable restore
#else
        public string Cpu { get; set; }
#endif
        /// <summary>The displayType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayType { get; set; }
#nullable restore
#else
        public string DisplayType { get; set; }
#endif
        /// <summary>The gpu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gpu { get; set; }
#nullable restore
#else
        public string Gpu { get; set; }
#endif
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The ram property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ram { get; set; }
#nullable restore
#else
        public string Ram { get; set; }
#endif
        /// <summary>The refreshRateHz property</summary>
        public int? RefreshRateHz { get; set; }
        /// <summary>The screenSizeInches property</summary>
        public double? ScreenSizeInches { get; set; }
        /// <summary>The storage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Storage { get; set; }
#nullable restore
#else
        public string Storage { get; set; }
#endif
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCapacity", n => { BatteryCapacity = n.GetIntValue(); } },
                { "batteryType", n => { BatteryType = n.GetStringValue(); } },
                { "cpu", n => { Cpu = n.GetStringValue(); } },
                { "displayType", n => { DisplayType = n.GetStringValue(); } },
                { "gpu", n => { Gpu = n.GetStringValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "ram", n => { Ram = n.GetStringValue(); } },
                { "refreshRateHz", n => { RefreshRateHz = n.GetIntValue(); } },
                { "screenSizeInches", n => { ScreenSizeInches = n.GetDoubleValue(); } },
                { "storage", n => { Storage = n.GetStringValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batteryCapacity", BatteryCapacity);
            writer.WriteStringValue("batteryType", BatteryType);
            writer.WriteStringValue("cpu", Cpu);
            writer.WriteStringValue("displayType", DisplayType);
            writer.WriteStringValue("gpu", Gpu);
            writer.WriteIntValue("height", Height);
            writer.WriteStringValue("ram", Ram);
            writer.WriteIntValue("refreshRateHz", RefreshRateHz);
            writer.WriteDoubleValue("screenSizeInches", ScreenSizeInches);
            writer.WriteStringValue("storage", Storage);
            writer.WriteIntValue("width", Width);
        }
    }
}
#pragma warning restore CS0618
