// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MobilePhonesBrand
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Apple")]
        #pragma warning disable CS1591
        Apple,
        #pragma warning restore CS1591
        [EnumMember(Value = "Motorola")]
        #pragma warning disable CS1591
        Motorola,
        #pragma warning restore CS1591
        [EnumMember(Value = "Samsung")]
        #pragma warning disable CS1591
        Samsung,
        #pragma warning restore CS1591
        [EnumMember(Value = "Xiaomi")]
        #pragma warning disable CS1591
        Xiaomi,
        #pragma warning restore CS1591
    }
}
