// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MobilePhoneHistoryDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The camera property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Camera { get; set; }
#nullable restore
#else
        public string Camera { get; set; }
#endif
        /// <summary>The categoryId property</summary>
        public Guid? CategoryId { get; set; }
        /// <summary>The changedAt property</summary>
        public DateTimeOffset? ChangedAt { get; set; }
        /// <summary>The commonDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CommonDescriptionDto? CommonDescription { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CommonDescriptionDto CommonDescription { get; set; }
#endif
        /// <summary>The connectivity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ConnectivityDto? Connectivity { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ConnectivityDto Connectivity { get; set; }
#endif
        /// <summary>The description2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description2 { get; set; }
#nullable restore
#else
        public string Description2 { get; set; }
#endif
        /// <summary>The description3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description3 { get; set; }
#nullable restore
#else
        public string Description3 { get; set; }
#endif
        /// <summary>The electronicDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto? ElectronicDetails { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto ElectronicDetails { get; set; }
#endif
        /// <summary>The faceId property</summary>
        public bool? FaceId { get; set; }
        /// <summary>The fingerPrint property</summary>
        public bool? FingerPrint { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The mobilePhoneId property</summary>
        public Guid? MobilePhoneId { get; set; }
        /// <summary>The operation property</summary>
        public int? Operation { get; set; }
        /// <summary>The price property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto? Price { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto Price { get; set; }
#endif
        /// <summary>The satelliteNavigationSystems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SatelliteNavigationSystemDto? SatelliteNavigationSystems { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SatelliteNavigationSystemDto SatelliteNavigationSystems { get; set; }
#endif
        /// <summary>The sensors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SensorsDto? Sensors { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SensorsDto Sensors { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneHistoryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneHistoryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MobilePhoneHistoryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "camera", n => { Camera = n.GetStringValue(); } },
                { "categoryId", n => { CategoryId = n.GetGuidValue(); } },
                { "changedAt", n => { ChangedAt = n.GetDateTimeOffsetValue(); } },
                { "commonDescription", n => { CommonDescription = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CommonDescriptionDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CommonDescriptionDto.CreateFromDiscriminatorValue); } },
                { "connectivity", n => { Connectivity = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ConnectivityDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ConnectivityDto.CreateFromDiscriminatorValue); } },
                { "description2", n => { Description2 = n.GetStringValue(); } },
                { "description3", n => { Description3 = n.GetStringValue(); } },
                { "electronicDetails", n => { ElectronicDetails = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto.CreateFromDiscriminatorValue); } },
                { "faceId", n => { FaceId = n.GetBoolValue(); } },
                { "fingerPrint", n => { FingerPrint = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "mobilePhoneId", n => { MobilePhoneId = n.GetGuidValue(); } },
                { "operation", n => { Operation = n.GetIntValue(); } },
                { "price", n => { Price = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto.CreateFromDiscriminatorValue); } },
                { "satelliteNavigationSystems", n => { SatelliteNavigationSystems = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SatelliteNavigationSystemDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SatelliteNavigationSystemDto.CreateFromDiscriminatorValue); } },
                { "sensors", n => { Sensors = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SensorsDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SensorsDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("camera", Camera);
            writer.WriteGuidValue("categoryId", CategoryId);
            writer.WriteDateTimeOffsetValue("changedAt", ChangedAt);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.CommonDescriptionDto>("commonDescription", CommonDescription);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ConnectivityDto>("connectivity", Connectivity);
            writer.WriteStringValue("description2", Description2);
            writer.WriteStringValue("description3", Description3);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ElectronicDetailsDto>("electronicDetails", ElectronicDetails);
            writer.WriteBoolValue("faceId", FaceId);
            writer.WriteBoolValue("fingerPrint", FingerPrint);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteGuidValue("mobilePhoneId", MobilePhoneId);
            writer.WriteIntValue("operation", Operation);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto>("price", Price);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SatelliteNavigationSystemDto>("satelliteNavigationSystems", SatelliteNavigationSystems);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.SensorsDto>("sensors", Sensors);
        }
    }
}
#pragma warning restore CS0618
