// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TopMobilePhoneDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The commonDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhonesCommonDescriptionDto? CommonDescription { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhonesCommonDescriptionDto CommonDescription { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The price property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto? Price { get; set; }
#nullable restore
#else
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto Price { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhoneDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhoneDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhoneDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commonDescription", n => { CommonDescription = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhonesCommonDescriptionDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhonesCommonDescriptionDto.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "price", n => { Price = n.GetObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.TopMobilePhonesCommonDescriptionDto>("commonDescription", CommonDescription);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.MoneyDto>("price", Price);
        }
    }
}
#pragma warning restore CS0618
