// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateSensorsExternalDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accelerometer property</summary>
        public bool? Accelerometer { get; set; }
        /// <summary>The ambientLight property</summary>
        public bool? AmbientLight { get; set; }
        /// <summary>The barometer property</summary>
        public bool? Barometer { get; set; }
        /// <summary>The compass property</summary>
        public bool? Compass { get; set; }
        /// <summary>The gyroscope property</summary>
        public bool? Gyroscope { get; set; }
        /// <summary>The halla property</summary>
        public bool? Halla { get; set; }
        /// <summary>The proximity property</summary>
        public bool? Proximity { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateSensorsExternalDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateSensorsExternalDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateSensorsExternalDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accelerometer", n => { Accelerometer = n.GetBoolValue(); } },
                { "ambientLight", n => { AmbientLight = n.GetBoolValue(); } },
                { "barometer", n => { Barometer = n.GetBoolValue(); } },
                { "compass", n => { Compass = n.GetBoolValue(); } },
                { "gyroscope", n => { Gyroscope = n.GetBoolValue(); } },
                { "halla", n => { Halla = n.GetBoolValue(); } },
                { "proximity", n => { Proximity = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("accelerometer", Accelerometer);
            writer.WriteBoolValue("ambientLight", AmbientLight);
            writer.WriteBoolValue("barometer", Barometer);
            writer.WriteBoolValue("compass", Compass);
            writer.WriteBoolValue("gyroscope", Gyroscope);
            writer.WriteBoolValue("halla", Halla);
            writer.WriteBoolValue("proximity", Proximity);
        }
    }
}
#pragma warning restore CS0618
