// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateConnectivityExternalDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bluetooth property</summary>
        public bool? Bluetooth { get; set; }
        /// <summary>The has5G property</summary>
        public bool? Has5G { get; set; }
        /// <summary>The nfc property</summary>
        public bool? Nfc { get; set; }
        /// <summary>The wiFi property</summary>
        public bool? WiFi { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateConnectivityExternalDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateConnectivityExternalDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.UpdateConnectivityExternalDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bluetooth", n => { Bluetooth = n.GetBoolValue(); } },
                { "has5G", n => { Has5G = n.GetBoolValue(); } },
                { "nfc", n => { Nfc = n.GetBoolValue(); } },
                { "wiFi", n => { WiFi = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("bluetooth", Bluetooth);
            writer.WriteBoolValue("has5G", Has5G);
            writer.WriteBoolValue("nfc", Nfc);
            writer.WriteBoolValue("wiFi", WiFi);
        }
    }
}
#pragma warning restore CS0618
