// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ValidationRuleDescriptor : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ruleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleName { get; set; }
#nullable restore
#else
        public string RuleName { get; set; }
#endif
        /// <summary>The rules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationError>? Rules { get; set; }
#nullable restore
#else
        public List<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationError> Rules { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationRuleDescriptor"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationRuleDescriptor CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationRuleDescriptor();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ruleName", n => { RuleName = n.GetStringValue(); } },
                { "rules", n => { Rules = n.GetCollectionOfObjectValues<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationError>(global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationError.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ruleName", RuleName);
            writer.WriteCollectionOfObjectValues<global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.Models.ValidationError>("rules", Rules);
        }
    }
}
#pragma warning restore CS0618
