// <auto-generated/>
#pragma warning disable CS0618
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow;
using ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ValidationPolicies;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation
{
    /// <summary>
    /// Builds and executes requests for operations under \products-documentation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsDocumentationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The flow property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder Flow
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.Flow.FlowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validationPolicies property</summary>
        public global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ValidationPolicies.ValidationPoliciesRequestBuilder ValidationPolicies
        {
            get => new global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ValidationPolicies.ValidationPoliciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ProductsDocumentationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsDocumentationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products-documentation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ECommerceStoreInvoice.Infrastructure.ApiClients.Products.ProductsDocumentation.ProductsDocumentationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsDocumentationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products-documentation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
